### ISSUE TITLE
Any way to extend the impulses?

### ISSUE THREAD

**Issue by ThommyTwoShoes** [bmillier/FFT-Convolution-Filter-Uniformly-partitioned#2]
Hi, I've tested your program a bit and aside from the compiler warning about about two unused variables and something with some comparisons, it's quite lovely as a cabinet simulator, I haven't tested the filters yet. I was wondering though, what becomes the bottleneck when going too far above the 18000 taps? I've tried overclocking to 816MHz, but it still hits the same limit, between 18040 and 18050 taps, where it begins to act strange, so the core clock doesn't seem to be the limiter. If it's a memory issue, would it make sense to try redefining the floats as 16 bit or dividing the matrixes into smaller partitions?
Thanks beforehand.

**Comment by bmillier** [comment]
Hi Thomas:
    The upper limit of about 18000 is dictated by the amount of memory available on the Teensy, plus the fact that it is segmented into 2 discrete regions and you can't overlap an array between them. Also, all of the FFT, iFFT routines are using super efficient CMSIS libraries that are floating point (yet run as quickly as fixed point). There is way too much computation going on inside these routines to do with 16-bit- there would be definite distortion that you could readily perceive.
Cheers
